### PR TITLE
Deregularise

### PR DESCRIPTION
**Pull request by marqh**
hi @ajdawson 

as part of reviewing 
https://github.com/SciTools/iris/pull/1587
I have become somewhat concerned about the 'regularise' behaviour.  

I very much support 1587 and this provides the means to control regrid operations on cubes, which is preferable to the auto-regularise approach in the old GRIB loader.  

We may have to work with some users as part of the deprecation to enable them to maintian their analysis if they are currently auto-regularising data sets, but I think that is a helpful process in the long term

With this in mind, I'm concerned about preserving the 'regularise' interface in the strict grib loading code base.  It is an odd fit for me, and is currently just not functioning;  I do not expect it to get attention to make it work usefully, or in the same way as the legacy GRIb loader, so including it at all seems strange to me.

I have put together a commit which removes this aspect.  It has never been released so it seems an ideal time to cut it out to me.

I would very much value your thougts on this. I am happy for this change to be included in your PR or to go up as a separate PR: which do you think might work better?

cheers
mark

### CODE REVIEW

**Comment by marqh** [comment]
ok, it seems I have taken my cut from a different point in the master than you and messed up the commit history, sorry.

if we want to use this PR, one of us can rebase to tidy this up. Perhaps we could discuss it first?

**Comment by ajdawson** [comment]
It was never my intention to include the ability to do the transform-on-load regularisation in the new GRIB loader, I simply did not consider this part as I have not provided an interface to it. As far as I am concerned it should be considered a legacy feature and not be present at all in the new loader.

**Comment by ajdawson** [comment]
@marqh - if you could clean this up it'd be great, I can't really get a handle on the changes with the spurious diffs.

**Comment by marqh** [comment]
> @marqh - if you could clean this up it'd be great, I can't really get a handle on the changes with the spurious diffs.

my git world has gone mad, i'm working on it, in the meantime, all my changes are in the one commit:
https://github.com/marqh/iris/commit/830a2382ea20956840033ec050e7c9aae9e86149

**Comment by marqh** [comment]
phew, that looks better

**Comment by marqh** [comment]
> As far as I am concerned it should be considered a legacy feature and not be present at all in the new loader.

my sentiments exactly, hence this proposed adaption to the strict loader

**Comment by ajdawson** [comment]
@marqh - Thanks for doing this, it seems OK to me, but I think it may as well be done in a separate PR since it is a reasonable size change. It would get more review scrutiny that way too. What do you think?

**Comment by marqh** [comment]
> @marqh - Thanks for doing this, it seems OK to me, but I think it may as well be done in a separate PR since it is a reasonable size change. It would get more review scrutiny that way too. What do you think?

i thought that might be the case
i'll push up a PR at iris

**Comment by marqh** [comment]
https://github.com/SciTools/iris/pull/1599

**Pull request closed without merging**
